name: Build project GeneratorUtil

on:
  push:
    branches: [ branchestestWorkflows ]
  pull_request:
    branches: [ branchestestWorkflows ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: npm install and npm run build
        run: |
          npm i
          npm run build:prod
      - name: Push Build to Releases
        uses: joelcamus/GeneratorUtil@v1.0
        with:
          artifacts: "dist/angular-githubaction/*"
          token: ${{ secrets.TOKEN }}
